### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by Ph0tonic**

### CODE REVIEW

**Comment by Ph0tonic** [comment]
I also propose to drop support for older versions of python that we do not use (3.7 and 3.6) to be able to use latest python syntax.

**Comment by volodymyrss** [comment]
> Ok, so tests for with the non-released version of jupyterhub are failing as well.
> 
>     * https://github.com/jupyterhub/batchspawner/actions/runs/7888451878/job/21526019676?pr=299

Uh. I wonder if we can just make a package "arcspawner" and only implement our spawner. Else we always have to merge upstream. What do you think?

**Comment by Ph0tonic** [comment]
I think that it would be a good idea and make much more sense :+1:

**Comment by Ph0tonic** [comment]
Shall we however merge this PR first ?

**Pull request merged**
