### PR TITLE
Improve spawn fail error message

### PR DESCRIPTION
**Pull request by Ph0tonic**
Add some logs to address :
- https://github.com/cta-epfl/flux-jh/issues/45

### CODE REVIEW

**Comment by volodymyrss** [comment]
hm, 100% test failure rate! :)

**Review by volodymyrss — CHANGES_REQUESTED** [review]
many test failures now

**Comment by Ph0tonic** [comment]
Test were already failing on master.

**Comment by volodymyrss** [comment]
> Test were already failing on master. But I can make another PR to address those.

Indeed, let's do it separately https://github.com/cta-epfl/batchspawner/issues/22

**Comment by Ph0tonic** [comment]
Shall we merge this now ?

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
